DROP TABLE X_PRED_STAT2;

CREATE TABLE X_PRED_STAT2
(
    YEAR VARCHAR2(4),
    MONTH VARCHAR2(2),
    DAY VARCHAR2(2),
    RUN_TIME DATE,
    PRED_M1 NUMBER,
    SE_M1 NUMBER,
    CI95L_M1 NUMBER,
    CI95U_M1 NUMBER,
    PRED_M2 NUMBER,
    SE_M2 NUMBER,
    CI95L_M2 NUMBER,
    CI95U_M2 NUMBER,
    PRIMARY KEY (YEAR, MONTH, DAY)
);
commit;