DROP TABLE X_VC_UPDATE;

CREATE TABLE X_VC_UPDATE
(
    YEAR VARCHAR2(4),
    MONTH VARCHAR2(2),
    DAY VARCHAR2(2),
    RETRIEVAL_TIME1 DATE,
    COUNT1 NUMBER,
    RETRIEVAL_TIME2 DATE,
    COUNT2 NUMBER,
    RETRIEVAL_TIME3 DATE,
    COUNT3 NUMBER,
    RETRIEVAL_TIME4 DATE,
    COUNT4 NUMBER,
    RETRIEVAL_TIME5 DATE,
    COUNT5 NUMBER,
    RETRIEVAL_TIME6 DATE,
    COUNT6 NUMBER,
    PRIMARY KEY (YEAR, MONTH, DAY)
);
commit;