WITH RN1 AS(
SELECT RowNo 
FROM (SELECT W1.*, ROWNUM RowNo FROM WEATHER_DATA_FORMATTED W1)
WHERE YEAR = EXTRACT (YEAR FROM SYSDATE-5)
      AND MONTH = EXTRACT (MONTH FROM SYSDATE-5)
      AND DAY = EXTRACT (DAY FROM SYSDATE-5)
      ),
RN2 AS(
SELECT RowNo 
FROM (SELECT W2.*, ROWNUM RowNo FROM WEATHER_DATA_FORMATTED W2)
WHERE YEAR = EXTRACT (YEAR FROM SYSDATE-2)
      AND MONTH = EXTRACT (MONTH FROM SYSDATE-2)
      AND DAY = EXTRACT (DAY FROM SYSDATE-2)
)
SELECT * FROM (SELECT W.*, ROWNUM RN FROM WEATHER_DATA_FORMATTED W) M, RN1, RN2
WHERE RN BETWEEN RN1.RowNo AND RN2.RowNo;
         