create or replace PROCEDURE X_TRACK_VC_UPDATE AS

BEGIN
  DECLARE
    I_YEAR VARCHAR(4);
    I_MONTH VARCHAR(2);
    I_DAY VARCHAR(2);
    I_DAILY_TOTAL NUMBER;
    
    ExistRow NUMBER;
  
    CURSOR c1
    IS     
      SELECT YEAR, MONTH, DAY, COUNT(CURR_IUCR)
      FROM CHRIS_DWH.CRIMES_ALLV
      WHERE (DATEOCC BETWEEN TO_DATE(TO_CHAR(sysdate-3, 'MM-DD-YYYY') || ' 00:00:00', 'MM-DD-YYYY hh24:mi:ss') AND TO_DATE(TO_CHAR(sysdate-1, 'MM-DD-YYYY') || ' 23:59:59', 'MM-DD-YYYY hh24:mi:ss')) 
        AND (CITY='CHICAGO') 
        AND (CURR_IUCR IN ('0110','0130','041A','041B','0420','0430','0440','0479','051A','051B','0520','0530','0545','0560','1753','1754') 
        OR CURR_IUCR LIKE '02__'
        OR CURR_IUCR LIKE '03__'
        OR CURR_IUCR LIKE '045_'
        OR CURR_IUCR LIKE '046_'
        OR CURR_IUCR LIKE '048_'
        OR CURR_IUCR LIKE '049_'
        OR CURR_IUCR LIKE '055_')
      GROUP BY YEAR, MONTH, DAY
      ORDER BY YEAR ASC, MONTH ASC, DAY ASC;
      
  BEGIN
    OPEN c1;
    LOOP
      FETCH c1 INTO I_YEAR, I_MONTH, I_DAY, I_DAILY_TOTAL;
      EXIT WHEN c1%NOTFOUND;
      
      SELECT COUNT(*) INTO ExistRow FROM X_VC_UPDATE WHERE YEAR=I_YEAR AND MONTH=I_MONTH AND DAY=I_DAY;
      IF ExistRow = 0 THEN   
          INSERT INTO X_VC_UPDATE (YEAR,MONTH,DAY,RETRIEVAL_TIME1,COUNT1,COUNT2,COUNT3,COUNT4,COUNT5,COUNT6)
          VALUES (I_YEAR,I_MONTH,I_DAY,sysdate,I_DAILY_TOTAL,NULL,NULL,NULL,NULL,NULL); 
      ELSE
          SELECT COUNT2,COUNT3,COUNT4,COUNT5,COUNT6 INTO cnt2,cnt3,cnt4,cnt5,cnt6 FROM X_VC_UPDATE WHERE YEAR=I_YEAR AND MONTH=I_MONTH AND DAY=I_DAY;
          IF cnt2 IS NULL THEN
            UPDATE X_VC_UPDATE SET RETRIEVAL_TIME2=sysdate, COUNT2=I_DAILY_TOTAL
            WHERE YEAR=I_YEAR AND MONTH=I_MONTH AND DAY=I_DAY;
          ELSIF cnt3 IS NULL THEN
            UPDATE X_VC_UPDATE SET RETRIEVAL_TIME3=sysdate, COUNT3=I_DAILY_TOTAL
            WHERE YEAR=I_YEAR AND MONTH=I_MONTH AND DAY=I_DAY;
          ELSIF cnt4 IS NULL THEN
            UPDATE X_VC_UPDATE SET RETRIEVAL_TIME4=sysdate, COUNT4=I_DAILY_TOTAL
            WHERE YEAR=I_YEAR AND MONTH=I_MONTH AND DAY=I_DAY;
          ELSIF cnt5 IS NULL THEN
            UPDATE X_VC_UPDATE SET RETRIEVAL_TIME5=sysdate, COUNT5=I_DAILY_TOTAL
            WHERE YEAR=I_YEAR AND MONTH=I_MONTH AND DAY=I_DAY;
          ELSE
            UPDATE X_VC_UPDATE SET RETRIEVAL_TIME6=sysdate, COUNT6=I_DAILY_TOTAL
            WHERE YEAR=I_YEAR AND MONTH=I_MONTH AND DAY=I_DAY;
          END IF;
      END IF;
      
    END LOOP;  
    CLOSE c1;
      
    COMMIT WORK; 
  END;
END X_TRACK_VC_UPDATE;