SELECT
YEAR,
MONTH,
DAY,
DAYOFWEEK,
CASE WHEN        (MONTH = 12  AND DAY = 31 AND DAYOFWEEK = 5) OR
                 (MONTH = 01  AND DAY = 02 AND DAYOFWEEK = 1) OR
                 (MONTH = 01  AND DAY = 01) 
     THEN 1
     WHEN        MONTH = 01 AND DAY BETWEEN 15 AND 21 AND DAYOFWEEK = 1 
     THEN 2
     WHEN        MONTH = 02 AND DAY BETWEEN 15 AND 21 AND DAYOFWEEK = 1
     THEN 3            
     WHEN        MONTH = 05 AND DAY BETWEEN 25 AND 31 AND DAYOFWEEK = 1 
     THEN 4
     WHEN        (MONTH = 07  AND DAY = 03 AND DAYOFWEEK = 5) OR
                 (MONTH = 07  AND DAY = 05 AND DAYOFWEEK = 1) OR
                 (MONTH = 07  AND DAY = 04)  
     THEN 5
     WHEN        MONTH = 09 AND DAY BETWEEN 1 AND 7 AND DAYOFWEEK = 1 
     THEN 6
     WHEN        MONTH = 10 AND DAY BETWEEN 8 AND 14 AND DAYOFWEEK = 2  
     THEN 7 
     WHEN        MONTH = 10  AND DAY = 31 
     THEN 8
     WHEN        (MONTH = 11  AND DAY = 10 AND DAYOFWEEK = 5) OR
                 (MONTH = 11  AND DAY = 12 AND DAYOFWEEK = 1) OR
                 (MONTH = 11  AND DAY = 11)  
     THEN 9
     WHEN        MONTH = 11 AND DAY BETWEEN 22 AND 28 AND DAYOFWEEK = 4 
     THEN 10    
     WHEN        (MONTH = 12  AND DAY = 24 AND DAYOFWEEK = 5) OR
                 (MONTH = 12  AND DAY = 26 AND DAYOFWEEK = 1) OR
                 (MONTH = 12  AND DAY = 25) 
     THEN 11
     ELSE 0 
     END AS HOLIDAY,
DAILY_TOTAL
FROM (
      SELECT TRUNC(DATEOCC),
      YEAR,
      MONTH,
      DAY,
      TO_CHAR(TO_DATE(YEAR||'/'||MONTH||'/'||DAY,'YYYY/MM/DD')-1,'D')  AS DAYOFWEEK,
      COUNT(CURR_IUCR) AS DAILY_TOTAL
      FROM CHRIS_DWH.CRIMES_ALLV
      WHERE (DATEOCC BETWEEN TO_DATE('01-01-2001 00:00:00', 'MM-DD-YYYY hh24:mi:ss') AND TO_DATE(TO_CHAR(SYSDATE-1, 'MM-DD-YYYY') || ' 23:59:59', 'MM-DD-YYYY hh24:mi:ss'))
      AND (CITY='CHICAGO') 
      AND (CURR_IUCR IN ('0110','0130','041A','041B','0420','0430','0440','0479','051A','051B','0520','0530','0545','0560','1753','1754') 
      OR CURR_IUCR LIKE '02__'
      OR CURR_IUCR LIKE '03__'
      OR CURR_IUCR LIKE '045_'
      OR CURR_IUCR LIKE '046_'
      OR CURR_IUCR LIKE '048_'
      OR CURR_IUCR LIKE '049_'
      OR CURR_IUCR LIKE '055_')
      GROUP BY TRUNC(DATEOCC), YEAR, MONTH, DAY, TO_CHAR(TO_DATE(YEAR||'/'||MONTH||'/'||DAY,'YYYY/MM/DD')-1,'D')
      ORDER BY TRUNC(DATEOCC) ASC
);